name: first-pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: linting
      uses: Jerome1337/golint-action@v1.0.3

    - name: build
      run: |
        docker build --tag=samplerestapi:latest .

    - name: Push To Github registry
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: samplerestapi
        tags: latest
        registry: ghcr.io/raja-pandian
        #username: rajapandian.veeraiah@gmail.com
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
